export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_OK = 'ADD_PRODUCT_OK';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const DOWNLOAD_PRODUCTS = 'DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_OK = 'DOWNLOAD_PRODUCTS_OK';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';

export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_DELETE_OK = 'PRODUCT_DELETE_OK';
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';

export const PRODUCT_EDIT = 'PRODUCT_EDIT';
export const START_PRODUCT_EDIT =   'START_PRODUCT_EDIT';
export const PRODUCT_EDIT_OK = 'PRODUCT_EDIT_OK';
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR';